/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ServiceRequest {
    id: bigint;
    status: RequestStatus;
    client: Principal;
    serviceType: ServiceType;
    name?: string;
    createdAt: Time;
    description: string;
    deadline: Time;
    email?: string;
    company?: string;
    phone?: string;
}
export interface ComplianceDeliverable {
    id: bigint;
    status: DeliverableStatus;
    client: Principal;
    title: string;
    dueDate: Time;
    deliverableType: DeliverableType;
}
export type Time = bigint;
export interface TechnicalReliabilityMetrics {
    pageLoadMs: bigint;
    sslStatus: boolean;
    mobileScore: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaymentRecord {
    id: bigint;
    status: PaymentStatus;
    client: Principal;
    paymentMethod: PaymentMethod;
    cardType?: string;
    timestamp: Time;
    currencyCode: string;
    amount: bigint;
}
export interface LeadGenerationMetrics {
    leadQualityBreakup: {
        low: bigint;
        high: bigint;
        medium: bigint;
    };
    formSubmissions: bigint;
    clickToCallCount: bigint;
}
export interface ClientRetentionMetrics {
    portalFunnelDropoffs: bigint;
    returningUserRatio: number;
}
export interface TimelineEntry {
    id: bigint;
    status: TimelineStatus;
    title: string;
    endDate: Time;
    description: string;
    clientPrincipal?: Principal;
    taskReference?: bigint;
    startDate: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TrustMetrics {
    testimonialClicks: bigint;
    blogEngagement: bigint;
    aboutPageAvgTime: bigint;
}
export interface ClientDocument {
    id: bigint;
    client: Principal;
    file: ExternalBlob;
    name: string;
    docType: DocumentType;
    uploadedAt: Time;
}
export interface ClientDeliverableInput {
    title: string;
    file: ExternalBlob;
    description: string;
}
export interface ClientDeliverable {
    id: bigint;
    status: ClientDeliverableStatus;
    title: string;
    submitter: Principal;
    file: ExternalBlob;
    createdAt: Time;
    description: string;
}
export interface FollowUpItem {
    id: bigint;
    status: FollowUpStatus;
    title: string;
    dueDate: Time;
    description: string;
    clientPrincipal?: Principal;
    notes: string;
    clientReference?: Principal;
}
export type UploadDocumentResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "notApproved";
    notApproved: null;
};
export interface AdminPaymentSettings {
    paypalEmail: string;
}
export interface ToDoItem {
    id: bigint;
    status: ToDoStatus;
    title: string;
    createdAt: Time;
    description: string;
    clientPrincipal?: Principal;
    assignedClient?: Principal;
    priority: ToDoPriority;
}
export interface AdminClientDeliverableInput {
    title: string;
    file: ExternalBlob;
    description: string;
    clientPrincipal: Principal;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface SearchIntentMetrics {
    localSeoRankings: bigint;
    seasonalKeywordTrends: Array<string>;
    aiVisibilityScore: bigint;
}
export interface ServiceRequestInput {
    serviceType: ServiceType;
    name: string;
    description: string;
    deadline: Time;
    email: string;
    company: string;
    phone: string;
}
export interface UserProfile {
    name: string;
    email: string;
    company: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ClientDeliverableStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum DeliverableStatus {
    completed = "completed",
    approved = "approved",
    inReview = "inReview",
    rejected = "rejected",
    drafting = "drafting"
}
export enum DeliverableType {
    consulting = "consulting",
    annual = "annual",
    quarterly = "quarterly",
    monthly = "monthly"
}
export enum DocumentType {
    payrollReport = "payrollReport",
    auditDoc = "auditDoc",
    taxFiling = "taxFiling"
}
export enum FollowUpStatus {
    pending = "pending",
    completed = "completed"
}
export enum PaymentMethod {
    creditCard = "creditCard",
    applePay = "applePay",
    googlePay = "googlePay",
    debitCard = "debitCard",
    paypal = "paypal"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum RequestStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum ServiceType {
    bankReconciliation = "bankReconciliation",
    incomeTaxFiling = "incomeTaxFiling",
    other = "other",
    audits = "audits",
    corporateTaxFiling = "corporateTaxFiling",
    payrollAdmin = "payrollAdmin",
    ledgerMaintenance = "ledgerMaintenance"
}
export enum TimelineStatus {
    completed = "completed",
    planned = "planned",
    inProgress = "inProgress"
}
export enum ToDoPriority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum ToDoStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createClientFollowUp(title: string, description: string, dueDate: Time, status: FollowUpStatus, notes: string): Promise<bigint>;
    createClientTimeline(title: string, description: string, startDate: Time, endDate: Time, status: TimelineStatus): Promise<bigint>;
    createClientToDo(title: string, description: string, priority: ToDoPriority, status: ToDoStatus): Promise<bigint>;
    createDeliverable(clientPrincipal: Principal, title: string, dueDate: Time, deliverableType: DeliverableType): Promise<bigint>;
    createFollowUp(title: string, description: string, dueDate: Time, clientReference: Principal | null, status: FollowUpStatus, notes: string): Promise<bigint>;
    createPayment(amount: bigint, currencyCode: string, paymentMethod: PaymentMethod, cardType: string | null): Promise<bigint>;
    createRequest(serviceType: ServiceType, description: string, deadline: Time): Promise<bigint>;
    createTimelineEntry(title: string, description: string, startDate: Time, endDate: Time, status: TimelineStatus, taskReference: bigint | null): Promise<bigint>;
    createToDo(title: string, description: string, priority: ToDoPriority, status: ToDoStatus, assignedClient: Principal | null): Promise<bigint>;
    createVisitorRequest(input: ServiceRequestInput): Promise<bigint>;
    getAdminPaymentSettings(): Promise<AdminPaymentSettings | null>;
    getAllComplianceDeliverables(): Promise<Array<ComplianceDeliverable>>;
    getAllDeliverables(): Promise<Array<ComplianceDeliverable>>;
    getAllDocuments(): Promise<Array<ClientDocument>>;
    getAllFollowUps(): Promise<Array<FollowUpItem>>;
    getAllPayments(): Promise<Array<PaymentRecord>>;
    getAllRequests(): Promise<Array<ServiceRequest>>;
    getAllSubmittedDeliverables(): Promise<Array<ClientDeliverable>>;
    getAllTimelines(): Promise<Array<TimelineEntry>>;
    getAllToDos(): Promise<Array<ToDoItem>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientDeliverables(client: Principal): Promise<Array<ComplianceDeliverable>>;
    getClientRequests(client: Principal): Promise<Array<ServiceRequest>>;
    getClientSubmissions(owner: Principal): Promise<Array<ClientDeliverable>>;
    getMyDeliverables(): Promise<Array<ComplianceDeliverable>>;
    getMyFollowUps(): Promise<Array<FollowUpItem>>;
    getMyPayments(): Promise<Array<PaymentRecord>>;
    getMyPendingDeliverables(): Promise<Array<ComplianceDeliverable>>;
    getMyRequests(): Promise<Array<ServiceRequest>>;
    getMySubmittedDeliverables(): Promise<Array<ClientDeliverable>>;
    getMyTimelines(): Promise<Array<TimelineEntry>>;
    getMyToDos(): Promise<Array<ToDoItem>>;
    getNewAnalyticsSummary(): Promise<{
        searchIntent: SearchIntentMetrics;
        trust: TrustMetrics;
        technicalReliability: TechnicalReliabilityMetrics;
        leadGeneration: LeadGenerationMetrics;
        clientRetention: ClientRetentionMetrics;
    }>;
    getPendingDeliverables(client: Principal): Promise<Array<ComplianceDeliverable>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProfileByPrincipal(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAdminPaymentSettings(settings: AdminPaymentSettings): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    submitDeliverable(input: ClientDeliverableInput): Promise<bigint>;
    submitDeliverableForClient(input: AdminClientDeliverableInput): Promise<bigint>;
    updateClientDeliverableStatus(deliverableId: bigint, newStatus: ClientDeliverableStatus): Promise<void>;
    updateFollowUpStatus(followUpId: bigint, newStatus: FollowUpStatus): Promise<void>;
    updatePaymentStatus(paymentId: bigint, status: PaymentStatus): Promise<void>;
    updateStatus(requestId: bigint, status: RequestStatus): Promise<void>;
    updateTimelineStatus(timelineId: bigint, newStatus: TimelineStatus): Promise<void>;
    updateToDoStatus(toDoId: bigint, newStatus: ToDoStatus): Promise<void>;
    uploadDocument(docType: DocumentType, name: string, file: ExternalBlob): Promise<UploadDocumentResult>;
}
import type { AdminClientDeliverableInput as _AdminClientDeliverableInput, AdminPaymentSettings as _AdminPaymentSettings, ApprovalStatus as _ApprovalStatus, ClientDeliverable as _ClientDeliverable, ClientDeliverableInput as _ClientDeliverableInput, ClientDeliverableStatus as _ClientDeliverableStatus, ClientDocument as _ClientDocument, ComplianceDeliverable as _ComplianceDeliverable, DeliverableStatus as _DeliverableStatus, DeliverableType as _DeliverableType, DocumentType as _DocumentType, ExternalBlob as _ExternalBlob, FollowUpItem as _FollowUpItem, FollowUpStatus as _FollowUpStatus, PaymentMethod as _PaymentMethod, PaymentRecord as _PaymentRecord, PaymentStatus as _PaymentStatus, RequestStatus as _RequestStatus, ServiceRequest as _ServiceRequest, ServiceRequestInput as _ServiceRequestInput, ServiceType as _ServiceType, Time as _Time, TimelineEntry as _TimelineEntry, TimelineStatus as _TimelineStatus, ToDoItem as _ToDoItem, ToDoPriority as _ToDoPriority, ToDoStatus as _ToDoStatus, UploadDocumentResult as _UploadDocumentResult, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClientFollowUp(arg0: string, arg1: string, arg2: Time, arg3: FollowUpStatus, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClientFollowUp(arg0, arg1, arg2, to_candid_FollowUpStatus_n10(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClientFollowUp(arg0, arg1, arg2, to_candid_FollowUpStatus_n10(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async createClientTimeline(arg0: string, arg1: string, arg2: Time, arg3: Time, arg4: TimelineStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClientTimeline(arg0, arg1, arg2, arg3, to_candid_TimelineStatus_n12(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClientTimeline(arg0, arg1, arg2, arg3, to_candid_TimelineStatus_n12(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createClientToDo(arg0: string, arg1: string, arg2: ToDoPriority, arg3: ToDoStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClientToDo(arg0, arg1, to_candid_ToDoPriority_n14(this._uploadFile, this._downloadFile, arg2), to_candid_ToDoStatus_n16(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClientToDo(arg0, arg1, to_candid_ToDoPriority_n14(this._uploadFile, this._downloadFile, arg2), to_candid_ToDoStatus_n16(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createDeliverable(arg0: Principal, arg1: string, arg2: Time, arg3: DeliverableType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeliverable(arg0, arg1, arg2, to_candid_DeliverableType_n18(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeliverable(arg0, arg1, arg2, to_candid_DeliverableType_n18(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createFollowUp(arg0: string, arg1: string, arg2: Time, arg3: Principal | null, arg4: FollowUpStatus, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFollowUp(arg0, arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3), to_candid_FollowUpStatus_n10(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFollowUp(arg0, arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3), to_candid_FollowUpStatus_n10(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async createPayment(arg0: bigint, arg1: string, arg2: PaymentMethod, arg3: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, arg1, to_candid_PaymentMethod_n21(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, arg1, to_candid_PaymentMethod_n21(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createRequest(arg0: ServiceType, arg1: string, arg2: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRequest(to_candid_ServiceType_n24(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRequest(to_candid_ServiceType_n24(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async createTimelineEntry(arg0: string, arg1: string, arg2: Time, arg3: Time, arg4: TimelineStatus, arg5: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTimelineEntry(arg0, arg1, arg2, arg3, to_candid_TimelineStatus_n12(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTimelineEntry(arg0, arg1, arg2, arg3, to_candid_TimelineStatus_n12(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createToDo(arg0: string, arg1: string, arg2: ToDoPriority, arg3: ToDoStatus, arg4: Principal | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createToDo(arg0, arg1, to_candid_ToDoPriority_n14(this._uploadFile, this._downloadFile, arg2), to_candid_ToDoStatus_n16(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createToDo(arg0, arg1, to_candid_ToDoPriority_n14(this._uploadFile, this._downloadFile, arg2), to_candid_ToDoStatus_n16(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createVisitorRequest(arg0: ServiceRequestInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVisitorRequest(to_candid_ServiceRequestInput_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVisitorRequest(to_candid_ServiceRequestInput_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAdminPaymentSettings(): Promise<AdminPaymentSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPaymentSettings();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPaymentSettings();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllComplianceDeliverables(): Promise<Array<ComplianceDeliverable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllComplianceDeliverables();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllComplianceDeliverables();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeliverables(): Promise<Array<ComplianceDeliverable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliverables();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliverables();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDocuments(): Promise<Array<ClientDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDocuments();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDocuments();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFollowUps(): Promise<Array<FollowUpItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFollowUps();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFollowUps();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRequests(): Promise<Array<ServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRequests();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRequests();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubmittedDeliverables(): Promise<Array<ClientDeliverable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmittedDeliverables();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmittedDeliverables();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTimelines(): Promise<Array<TimelineEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimelines();
                return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimelines();
            return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllToDos(): Promise<Array<ToDoItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllToDos();
                return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllToDos();
            return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientDeliverables(arg0: Principal): Promise<Array<ComplianceDeliverable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientDeliverables(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientDeliverables(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientRequests(arg0: Principal): Promise<Array<ServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientRequests(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientRequests(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientSubmissions(arg0: Principal): Promise<Array<ClientDeliverable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientSubmissions(arg0);
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientSubmissions(arg0);
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDeliverables(): Promise<Array<ComplianceDeliverable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDeliverables();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDeliverables();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyFollowUps(): Promise<Array<FollowUpItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFollowUps();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFollowUps();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPayments();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPayments();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPendingDeliverables(): Promise<Array<ComplianceDeliverable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPendingDeliverables();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPendingDeliverables();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRequests(): Promise<Array<ServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRequests();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRequests();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubmittedDeliverables(): Promise<Array<ClientDeliverable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmittedDeliverables();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmittedDeliverables();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTimelines(): Promise<Array<TimelineEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTimelines();
                return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTimelines();
            return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyToDos(): Promise<Array<ToDoItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyToDos();
                return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyToDos();
            return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewAnalyticsSummary(): Promise<{
        searchIntent: SearchIntentMetrics;
        trust: TrustMetrics;
        technicalReliability: TechnicalReliabilityMetrics;
        leadGeneration: LeadGenerationMetrics;
        clientRetention: ClientRetentionMetrics;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewAnalyticsSummary();
            return result;
        }
    }
    async getPendingDeliverables(arg0: Principal): Promise<Array<ComplianceDeliverable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDeliverables(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDeliverables(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileByPrincipal(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileByPrincipal(arg0);
                return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileByPrincipal(arg0);
            return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAdminPaymentSettings(arg0: AdminPaymentSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminPaymentSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminPaymentSettings(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n89(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n89(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitDeliverable(arg0: ClientDeliverableInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDeliverable(await to_candid_ClientDeliverableInput_n91(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDeliverable(await to_candid_ClientDeliverableInput_n91(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitDeliverableForClient(arg0: AdminClientDeliverableInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDeliverableForClient(await to_candid_AdminClientDeliverableInput_n94(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDeliverableForClient(await to_candid_AdminClientDeliverableInput_n94(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateClientDeliverableStatus(arg0: bigint, arg1: ClientDeliverableStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClientDeliverableStatus(arg0, to_candid_ClientDeliverableStatus_n96(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClientDeliverableStatus(arg0, to_candid_ClientDeliverableStatus_n96(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFollowUpStatus(arg0: bigint, arg1: FollowUpStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFollowUpStatus(arg0, to_candid_FollowUpStatus_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFollowUpStatus(arg0, to_candid_FollowUpStatus_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePaymentStatus(arg0: bigint, arg1: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n98(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n98(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStatus(arg0: bigint, arg1: RequestStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStatus(arg0, to_candid_RequestStatus_n100(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStatus(arg0, to_candid_RequestStatus_n100(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTimelineStatus(arg0: bigint, arg1: TimelineStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTimelineStatus(arg0, to_candid_TimelineStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTimelineStatus(arg0, to_candid_TimelineStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateToDoStatus(arg0: bigint, arg1: ToDoStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateToDoStatus(arg0, to_candid_ToDoStatus_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateToDoStatus(arg0, to_candid_ToDoStatus_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadDocument(arg0: DocumentType, arg1: string, arg2: ExternalBlob): Promise<UploadDocumentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(to_candid_DocumentType_n102(this._uploadFile, this._downloadFile, arg0), arg1, await to_candid_ExternalBlob_n93(this._uploadFile, this._downloadFile, arg2));
                return from_candid_UploadDocumentResult_n104(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(to_candid_DocumentType_n102(this._uploadFile, this._downloadFile, arg0), arg1, await to_candid_ExternalBlob_n93(this._uploadFile, this._downloadFile, arg2));
            return from_candid_UploadDocumentResult_n104(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApprovalStatus_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n88(_uploadFile, _downloadFile, value);
}
function from_candid_ClientDeliverableStatus_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientDeliverableStatus): ClientDeliverableStatus {
    return from_candid_variant_n68(_uploadFile, _downloadFile, value);
}
async function from_candid_ClientDeliverable_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientDeliverable): Promise<ClientDeliverable> {
    return await from_candid_record_n66(_uploadFile, _downloadFile, value);
}
async function from_candid_ClientDocument_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientDocument): Promise<ClientDocument> {
    return await from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ComplianceDeliverable_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplianceDeliverable): ComplianceDeliverable {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_DeliverableStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliverableStatus): DeliverableStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_DeliverableType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliverableType): DeliverableType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FollowUpItem_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUpItem): FollowUpItem {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_FollowUpStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUpStatus): FollowUpStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecord_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceRequest_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceRequest): ServiceRequest {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_TimelineEntry_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineEntry): TimelineEntry {
    return from_candid_record_n71(_uploadFile, _downloadFile, value);
}
function from_candid_TimelineStatus_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineStatus): TimelineStatus {
    return from_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function from_candid_ToDoItem_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToDoItem): ToDoItem {
    return from_candid_record_n76(_uploadFile, _downloadFile, value);
}
function from_candid_ToDoPriority_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToDoPriority): ToDoPriority {
    return from_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function from_candid_ToDoStatus_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToDoStatus): ToDoStatus {
    return from_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function from_candid_UploadDocumentResult_n104(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadDocumentResult): UploadDocumentResult {
    return from_candid_variant_n105(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n86(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n83(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminPaymentSettings]): AdminPaymentSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DeliverableStatus;
    client: Principal;
    title: string;
    dueDate: _Time;
    deliverableType: _DeliverableType;
}): {
    id: bigint;
    status: DeliverableStatus;
    client: Principal;
    title: string;
    dueDate: Time;
    deliverableType: DeliverableType;
} {
    return {
        id: value.id,
        status: from_candid_DeliverableStatus_n33(_uploadFile, _downloadFile, value.status),
        client: value.client,
        title: value.title,
        dueDate: value.dueDate,
        deliverableType: from_candid_DeliverableType_n35(_uploadFile, _downloadFile, value.deliverableType)
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    client: Principal;
    file: _ExternalBlob;
    name: string;
    docType: _DocumentType;
    uploadedAt: _Time;
}): Promise<{
    id: bigint;
    client: Principal;
    file: ExternalBlob;
    name: string;
    docType: DocumentType;
    uploadedAt: Time;
}> {
    return {
        id: value.id,
        client: value.client,
        file: await from_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value.file),
        name: value.name,
        docType: from_candid_DocumentType_n41(_uploadFile, _downloadFile, value.docType),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _FollowUpStatus;
    title: string;
    dueDate: _Time;
    description: string;
    clientPrincipal: [] | [Principal];
    notes: string;
    clientReference: [] | [Principal];
}): {
    id: bigint;
    status: FollowUpStatus;
    title: string;
    dueDate: Time;
    description: string;
    clientPrincipal?: Principal;
    notes: string;
    clientReference?: Principal;
} {
    return {
        id: value.id,
        status: from_candid_FollowUpStatus_n46(_uploadFile, _downloadFile, value.status),
        title: value.title,
        dueDate: value.dueDate,
        description: value.description,
        clientPrincipal: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.clientPrincipal)),
        notes: value.notes,
        clientReference: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.clientReference))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    client: Principal;
    paymentMethod: _PaymentMethod;
    cardType: [] | [string];
    timestamp: _Time;
    currencyCode: string;
    amount: bigint;
}): {
    id: bigint;
    status: PaymentStatus;
    client: Principal;
    paymentMethod: PaymentMethod;
    cardType?: string;
    timestamp: Time;
    currencyCode: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n52(_uploadFile, _downloadFile, value.status),
        client: value.client,
        paymentMethod: from_candid_PaymentMethod_n54(_uploadFile, _downloadFile, value.paymentMethod),
        cardType: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.cardType)),
        timestamp: value.timestamp,
        currencyCode: value.currencyCode,
        amount: value.amount
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RequestStatus;
    client: Principal;
    serviceType: _ServiceType;
    name: [] | [string];
    createdAt: _Time;
    description: string;
    deadline: _Time;
    email: [] | [string];
    company: [] | [string];
    phone: [] | [string];
}): {
    id: bigint;
    status: RequestStatus;
    client: Principal;
    serviceType: ServiceType;
    name?: string;
    createdAt: Time;
    description: string;
    deadline: Time;
    email?: string;
    company?: string;
    phone?: string;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n60(_uploadFile, _downloadFile, value.status),
        client: value.client,
        serviceType: from_candid_ServiceType_n62(_uploadFile, _downloadFile, value.serviceType),
        name: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.name)),
        createdAt: value.createdAt,
        description: value.description,
        deadline: value.deadline,
        email: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.email)),
        company: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.company)),
        phone: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.phone))
    };
}
async function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ClientDeliverableStatus;
    title: string;
    submitter: Principal;
    file: _ExternalBlob;
    createdAt: _Time;
    description: string;
}): Promise<{
    id: bigint;
    status: ClientDeliverableStatus;
    title: string;
    submitter: Principal;
    file: ExternalBlob;
    createdAt: Time;
    description: string;
}> {
    return {
        id: value.id,
        status: from_candid_ClientDeliverableStatus_n67(_uploadFile, _downloadFile, value.status),
        title: value.title,
        submitter: value.submitter,
        file: await from_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value.file),
        createdAt: value.createdAt,
        description: value.description
    };
}
function from_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TimelineStatus;
    title: string;
    endDate: _Time;
    description: string;
    clientPrincipal: [] | [Principal];
    taskReference: [] | [bigint];
    startDate: _Time;
}): {
    id: bigint;
    status: TimelineStatus;
    title: string;
    endDate: Time;
    description: string;
    clientPrincipal?: Principal;
    taskReference?: bigint;
    startDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_TimelineStatus_n72(_uploadFile, _downloadFile, value.status),
        title: value.title,
        endDate: value.endDate,
        description: value.description,
        clientPrincipal: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.clientPrincipal)),
        taskReference: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.taskReference)),
        startDate: value.startDate
    };
}
function from_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ToDoStatus;
    title: string;
    createdAt: _Time;
    description: string;
    clientPrincipal: [] | [Principal];
    assignedClient: [] | [Principal];
    priority: _ToDoPriority;
}): {
    id: bigint;
    status: ToDoStatus;
    title: string;
    createdAt: Time;
    description: string;
    clientPrincipal?: Principal;
    assignedClient?: Principal;
    priority: ToDoPriority;
} {
    return {
        id: value.id,
        status: from_candid_ToDoStatus_n77(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        clientPrincipal: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.clientPrincipal)),
        assignedClient: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.assignedClient)),
        priority: from_candid_ToDoPriority_n79(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n87(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n105(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    notApproved: null;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "notApproved";
    notApproved: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notApproved" in value ? {
        __kind__: "notApproved",
        notApproved: value.notApproved
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    approved: null;
} | {
    inReview: null;
} | {
    rejected: null;
} | {
    drafting: null;
}): DeliverableStatus {
    return "completed" in value ? DeliverableStatus.completed : "approved" in value ? DeliverableStatus.approved : "inReview" in value ? DeliverableStatus.inReview : "rejected" in value ? DeliverableStatus.rejected : "drafting" in value ? DeliverableStatus.drafting : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    consulting: null;
} | {
    annual: null;
} | {
    quarterly: null;
} | {
    monthly: null;
}): DeliverableType {
    return "consulting" in value ? DeliverableType.consulting : "annual" in value ? DeliverableType.annual : "quarterly" in value ? DeliverableType.quarterly : "monthly" in value ? DeliverableType.monthly : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    payrollReport: null;
} | {
    auditDoc: null;
} | {
    taxFiling: null;
}): DocumentType {
    return "payrollReport" in value ? DocumentType.payrollReport : "auditDoc" in value ? DocumentType.auditDoc : "taxFiling" in value ? DocumentType.taxFiling : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): FollowUpStatus {
    return "pending" in value ? FollowUpStatus.pending : "completed" in value ? FollowUpStatus.completed : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creditCard: null;
} | {
    applePay: null;
} | {
    googlePay: null;
} | {
    debitCard: null;
} | {
    paypal: null;
}): PaymentMethod {
    return "creditCard" in value ? PaymentMethod.creditCard : "applePay" in value ? PaymentMethod.applePay : "googlePay" in value ? PaymentMethod.googlePay : "debitCard" in value ? PaymentMethod.debitCard : "paypal" in value ? PaymentMethod.paypal : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): RequestStatus {
    return "cancelled" in value ? RequestStatus.cancelled : "pending" in value ? RequestStatus.pending : "completed" in value ? RequestStatus.completed : "inProgress" in value ? RequestStatus.inProgress : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankReconciliation: null;
} | {
    incomeTaxFiling: null;
} | {
    other: null;
} | {
    audits: null;
} | {
    corporateTaxFiling: null;
} | {
    payrollAdmin: null;
} | {
    ledgerMaintenance: null;
}): ServiceType {
    return "bankReconciliation" in value ? ServiceType.bankReconciliation : "incomeTaxFiling" in value ? ServiceType.incomeTaxFiling : "other" in value ? ServiceType.other : "audits" in value ? ServiceType.audits : "corporateTaxFiling" in value ? ServiceType.corporateTaxFiling : "payrollAdmin" in value ? ServiceType.payrollAdmin : "ledgerMaintenance" in value ? ServiceType.ledgerMaintenance : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): ClientDeliverableStatus {
    return "pending" in value ? ClientDeliverableStatus.pending : "rejected" in value ? ClientDeliverableStatus.rejected : "accepted" in value ? ClientDeliverableStatus.accepted : value;
}
function from_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    planned: null;
} | {
    inProgress: null;
}): TimelineStatus {
    return "completed" in value ? TimelineStatus.completed : "planned" in value ? TimelineStatus.planned : "inProgress" in value ? TimelineStatus.inProgress : value;
}
function from_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): ToDoStatus {
    return "pending" in value ? ToDoStatus.pending : "completed" in value ? ToDoStatus.completed : "inProgress" in value ? ToDoStatus.inProgress : value;
}
function from_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): ToDoPriority {
    return "low" in value ? ToDoPriority.low : "high" in value ? ToDoPriority.high : "medium" in value ? ToDoPriority.medium : value;
}
function from_candid_variant_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ComplianceDeliverable>): Array<ComplianceDeliverable> {
    return value.map((x)=>from_candid_ComplianceDeliverable_n31(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientDocument>): Promise<Array<ClientDocument>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ClientDocument_n38(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowUpItem>): Array<FollowUpItem> {
    return value.map((x)=>from_candid_FollowUpItem_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecord>): Array<PaymentRecord> {
    return value.map((x)=>from_candid_PaymentRecord_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceRequest>): Array<ServiceRequest> {
    return value.map((x)=>from_candid_ServiceRequest_n58(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientDeliverable>): Promise<Array<ClientDeliverable>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ClientDeliverable_n65(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimelineEntry>): Array<TimelineEntry> {
    return value.map((x)=>from_candid_TimelineEntry_n70(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ToDoItem>): Array<ToDoItem> {
    return value.map((x)=>from_candid_ToDoItem_n75(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n85(_uploadFile, _downloadFile, x));
}
async function to_candid_AdminClientDeliverableInput_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminClientDeliverableInput): Promise<_AdminClientDeliverableInput> {
    return await to_candid_record_n95(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n90(_uploadFile, _downloadFile, value);
}
async function to_candid_ClientDeliverableInput_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientDeliverableInput): Promise<_ClientDeliverableInput> {
    return await to_candid_record_n92(_uploadFile, _downloadFile, value);
}
function to_candid_ClientDeliverableStatus_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientDeliverableStatus): _ClientDeliverableStatus {
    return to_candid_variant_n97(_uploadFile, _downloadFile, value);
}
function to_candid_DeliverableType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliverableType): _DeliverableType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentType_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n103(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FollowUpStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FollowUpStatus): _FollowUpStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n99(_uploadFile, _downloadFile, value);
}
function to_candid_RequestStatus_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): _RequestStatus {
    return to_candid_variant_n101(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceRequestInput_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceRequestInput): _ServiceRequestInput {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_TimelineStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimelineStatus): _TimelineStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ToDoPriority_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToDoPriority): _ToDoPriority {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ToDoStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToDoStatus): _ToDoStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceType: ServiceType;
    name: string;
    description: string;
    deadline: Time;
    email: string;
    company: string;
    phone: string;
}): {
    serviceType: _ServiceType;
    name: string;
    description: string;
    deadline: _Time;
    email: string;
    company: string;
    phone: string;
} {
    return {
        serviceType: to_candid_ServiceType_n24(_uploadFile, _downloadFile, value.serviceType),
        name: value.name,
        description: value.description,
        deadline: value.deadline,
        email: value.email,
        company: value.company,
        phone: value.phone
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    file: ExternalBlob;
    description: string;
}): Promise<{
    title: string;
    file: _ExternalBlob;
    description: string;
}> {
    return {
        title: value.title,
        file: await to_candid_ExternalBlob_n93(_uploadFile, _downloadFile, value.file),
        description: value.description
    };
}
async function to_candid_record_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    file: ExternalBlob;
    description: string;
    clientPrincipal: Principal;
}): Promise<{
    title: string;
    file: _ExternalBlob;
    description: string;
    clientPrincipal: Principal;
}> {
    return {
        title: value.title,
        file: await to_candid_ExternalBlob_n93(_uploadFile, _downloadFile, value.file),
        description: value.description,
        clientPrincipal: value.clientPrincipal
    };
}
function to_candid_variant_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == RequestStatus.cancelled ? {
        cancelled: null
    } : value == RequestStatus.pending ? {
        pending: null
    } : value == RequestStatus.completed ? {
        completed: null
    } : value == RequestStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n103(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): {
    payrollReport: null;
} | {
    auditDoc: null;
} | {
    taxFiling: null;
} {
    return value == DocumentType.payrollReport ? {
        payrollReport: null
    } : value == DocumentType.auditDoc ? {
        auditDoc: null
    } : value == DocumentType.taxFiling ? {
        taxFiling: null
    } : value;
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FollowUpStatus): {
    pending: null;
} | {
    completed: null;
} {
    return value == FollowUpStatus.pending ? {
        pending: null
    } : value == FollowUpStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimelineStatus): {
    completed: null;
} | {
    planned: null;
} | {
    inProgress: null;
} {
    return value == TimelineStatus.completed ? {
        completed: null
    } : value == TimelineStatus.planned ? {
        planned: null
    } : value == TimelineStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToDoPriority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == ToDoPriority.low ? {
        low: null
    } : value == ToDoPriority.high ? {
        high: null
    } : value == ToDoPriority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToDoStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == ToDoStatus.pending ? {
        pending: null
    } : value == ToDoStatus.completed ? {
        completed: null
    } : value == ToDoStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliverableType): {
    consulting: null;
} | {
    annual: null;
} | {
    quarterly: null;
} | {
    monthly: null;
} {
    return value == DeliverableType.consulting ? {
        consulting: null
    } : value == DeliverableType.annual ? {
        annual: null
    } : value == DeliverableType.quarterly ? {
        quarterly: null
    } : value == DeliverableType.monthly ? {
        monthly: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    creditCard: null;
} | {
    applePay: null;
} | {
    googlePay: null;
} | {
    debitCard: null;
} | {
    paypal: null;
} {
    return value == PaymentMethod.creditCard ? {
        creditCard: null
    } : value == PaymentMethod.applePay ? {
        applePay: null
    } : value == PaymentMethod.googlePay ? {
        googlePay: null
    } : value == PaymentMethod.debitCard ? {
        debitCard: null
    } : value == PaymentMethod.paypal ? {
        paypal: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    bankReconciliation: null;
} | {
    incomeTaxFiling: null;
} | {
    other: null;
} | {
    audits: null;
} | {
    corporateTaxFiling: null;
} | {
    payrollAdmin: null;
} | {
    ledgerMaintenance: null;
} {
    return value == ServiceType.bankReconciliation ? {
        bankReconciliation: null
    } : value == ServiceType.incomeTaxFiling ? {
        incomeTaxFiling: null
    } : value == ServiceType.other ? {
        other: null
    } : value == ServiceType.audits ? {
        audits: null
    } : value == ServiceType.corporateTaxFiling ? {
        corporateTaxFiling: null
    } : value == ServiceType.payrollAdmin ? {
        payrollAdmin: null
    } : value == ServiceType.ledgerMaintenance ? {
        ledgerMaintenance: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientDeliverableStatus): {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == ClientDeliverableStatus.pending ? {
        pending: null
    } : value == ClientDeliverableStatus.rejected ? {
        rejected: null
    } : value == ClientDeliverableStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.completed ? {
        completed: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
