/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const DeliverableType = IDL.Variant({
  'consulting' : IDL.Null,
  'annual' : IDL.Null,
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'creditCard' : IDL.Null,
  'applePay' : IDL.Null,
  'googlePay' : IDL.Null,
  'debitCard' : IDL.Null,
  'paypal' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'bankReconciliation' : IDL.Null,
  'incomeTaxFiling' : IDL.Null,
  'other' : IDL.Null,
  'audits' : IDL.Null,
  'corporateTaxFiling' : IDL.Null,
  'payrollAdmin' : IDL.Null,
  'ledgerMaintenance' : IDL.Null,
});
export const ServiceRequestInput = IDL.Record({
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : Time,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'phone' : IDL.Text,
});
export const AdminPaymentSettings = IDL.Record({ 'paypalEmail' : IDL.Text });
export const DeliverableStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'awaitingReview' : IDL.Null,
  'completed' : IDL.Null,
  'overdue' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ComplianceDeliverable = IDL.Record({
  'id' : IDL.Nat,
  'status' : DeliverableStatus,
  'client' : IDL.Principal,
  'title' : IDL.Text,
  'dueDate' : Time,
  'deliverableType' : DeliverableType,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentType = IDL.Variant({
  'payrollReport' : IDL.Null,
  'auditDoc' : IDL.Null,
  'taxFiling' : IDL.Null,
});
export const ClientDocument = IDL.Record({
  'id' : IDL.Nat,
  'client' : IDL.Principal,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'docType' : DocumentType,
  'uploadedAt' : Time,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'client' : IDL.Principal,
  'paymentMethod' : PaymentMethod,
  'cardType' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'currencyCode' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const RequestStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'client' : IDL.Principal,
  'serviceType' : ServiceType,
  'name' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'description' : IDL.Text,
  'deadline' : Time,
  'email' : IDL.Opt(IDL.Text),
  'company' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
});
export const UploadDocumentResult = IDL.Variant({
  'ok' : IDL.Nat,
  'notApproved' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveClient' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDeliverable' : IDL.Func(
      [IDL.Text, Time, DeliverableType],
      [IDL.Nat],
      [],
    ),
  'createPayment' : IDL.Func(
      [IDL.Nat, IDL.Text, PaymentMethod, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createRequest' : IDL.Func([ServiceType, IDL.Text, Time], [IDL.Nat], []),
  'createVisitorRequest' : IDL.Func([ServiceRequestInput], [IDL.Nat], []),
  'getAdminPaymentSettings' : IDL.Func(
      [],
      [IDL.Opt(AdminPaymentSettings)],
      ['query'],
    ),
  'getAllDeliverables' : IDL.Func(
      [],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(ClientDocument)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getAllPendingClients' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientApprovalStatus' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'getClientDeliverables' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getClientRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getMyDeliverables' : IDL.Func(
      [],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getMyPendingDeliverables' : IDL.Func(
      [],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getMyRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getPendingDeliverables' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'rejectClient' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminPaymentSettings' : IDL.Func([AdminPaymentSettings], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateDeliverableStatus' : IDL.Func([IDL.Nat, DeliverableStatus], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updateStatus' : IDL.Func([IDL.Nat, RequestStatus], [], []),
  'uploadDocument' : IDL.Func(
      [DocumentType, IDL.Text, ExternalBlob],
      [UploadDocumentResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const DeliverableType = IDL.Variant({
    'consulting' : IDL.Null,
    'annual' : IDL.Null,
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'creditCard' : IDL.Null,
    'applePay' : IDL.Null,
    'googlePay' : IDL.Null,
    'debitCard' : IDL.Null,
    'paypal' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'bankReconciliation' : IDL.Null,
    'incomeTaxFiling' : IDL.Null,
    'other' : IDL.Null,
    'audits' : IDL.Null,
    'corporateTaxFiling' : IDL.Null,
    'payrollAdmin' : IDL.Null,
    'ledgerMaintenance' : IDL.Null,
  });
  const ServiceRequestInput = IDL.Record({
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : Time,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AdminPaymentSettings = IDL.Record({ 'paypalEmail' : IDL.Text });
  const DeliverableStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'awaitingReview' : IDL.Null,
    'completed' : IDL.Null,
    'overdue' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ComplianceDeliverable = IDL.Record({
    'id' : IDL.Nat,
    'status' : DeliverableStatus,
    'client' : IDL.Principal,
    'title' : IDL.Text,
    'dueDate' : Time,
    'deliverableType' : DeliverableType,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentType = IDL.Variant({
    'payrollReport' : IDL.Null,
    'auditDoc' : IDL.Null,
    'taxFiling' : IDL.Null,
  });
  const ClientDocument = IDL.Record({
    'id' : IDL.Nat,
    'client' : IDL.Principal,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'docType' : DocumentType,
    'uploadedAt' : Time,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'client' : IDL.Principal,
    'paymentMethod' : PaymentMethod,
    'cardType' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'currencyCode' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const RequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'client' : IDL.Principal,
    'serviceType' : ServiceType,
    'name' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'description' : IDL.Text,
    'deadline' : Time,
    'email' : IDL.Opt(IDL.Text),
    'company' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
  });
  const UploadDocumentResult = IDL.Variant({
    'ok' : IDL.Nat,
    'notApproved' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveClient' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDeliverable' : IDL.Func(
        [IDL.Text, Time, DeliverableType],
        [IDL.Nat],
        [],
      ),
    'createPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, PaymentMethod, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createRequest' : IDL.Func([ServiceType, IDL.Text, Time], [IDL.Nat], []),
    'createVisitorRequest' : IDL.Func([ServiceRequestInput], [IDL.Nat], []),
    'getAdminPaymentSettings' : IDL.Func(
        [],
        [IDL.Opt(AdminPaymentSettings)],
        ['query'],
      ),
    'getAllDeliverables' : IDL.Func(
        [],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(ClientDocument)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getAllPendingClients' : IDL.Func(
        [],
        [IDL.Vec(UserApprovalInfo)],
        ['query'],
      ),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientApprovalStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'getClientDeliverables' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getClientRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getMyDeliverables' : IDL.Func(
        [],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getMyPendingDeliverables' : IDL.Func(
        [],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getMyRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getPendingDeliverables' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'rejectClient' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminPaymentSettings' : IDL.Func([AdminPaymentSettings], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateDeliverableStatus' : IDL.Func([IDL.Nat, DeliverableStatus], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updateStatus' : IDL.Func([IDL.Nat, RequestStatus], [], []),
    'uploadDocument' : IDL.Func(
        [DocumentType, IDL.Text, ExternalBlob],
        [UploadDocumentResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };