/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPaymentSettings { 'paypalEmail' : string }
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ClientDocument {
  'id' : bigint,
  'client' : Principal,
  'file' : ExternalBlob,
  'name' : string,
  'docType' : DocumentType,
  'uploadedAt' : Time,
}
export interface ComplianceDeliverable {
  'id' : bigint,
  'status' : DeliverableStatus,
  'client' : Principal,
  'title' : string,
  'dueDate' : Time,
  'deliverableType' : DeliverableType,
}
export type DeliverableStatus = { 'notStarted' : null } |
  { 'awaitingReview' : null } |
  { 'completed' : null } |
  { 'overdue' : null } |
  { 'inProgress' : null };
export type DeliverableType = { 'consulting' : null } |
  { 'annual' : null } |
  { 'quarterly' : null } |
  { 'monthly' : null };
export type DocumentType = { 'payrollReport' : null } |
  { 'auditDoc' : null } |
  { 'taxFiling' : null };
export type ExternalBlob = Uint8Array;
export type PaymentMethod = { 'creditCard' : null } |
  { 'applePay' : null } |
  { 'googlePay' : null } |
  { 'debitCard' : null } |
  { 'paypal' : null };
export interface PaymentRecord {
  'id' : bigint,
  'status' : PaymentStatus,
  'client' : Principal,
  'paymentMethod' : PaymentMethod,
  'cardType' : [] | [string],
  'timestamp' : Time,
  'currencyCode' : string,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type RequestStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface ServiceRequest {
  'id' : bigint,
  'status' : RequestStatus,
  'client' : Principal,
  'serviceType' : ServiceType,
  'name' : [] | [string],
  'createdAt' : Time,
  'description' : string,
  'deadline' : Time,
  'email' : [] | [string],
  'company' : [] | [string],
  'phone' : [] | [string],
}
export interface ServiceRequestInput {
  'serviceType' : ServiceType,
  'name' : string,
  'description' : string,
  'deadline' : Time,
  'email' : string,
  'company' : string,
  'phone' : string,
}
export type ServiceType = { 'bankReconciliation' : null } |
  { 'incomeTaxFiling' : null } |
  { 'other' : null } |
  { 'audits' : null } |
  { 'corporateTaxFiling' : null } |
  { 'payrollAdmin' : null } |
  { 'ledgerMaintenance' : null };
export type Time = bigint;
export type UploadDocumentResult = { 'ok' : bigint } |
  { 'notApproved' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveClient' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDeliverable' : ActorMethod<[string, Time, DeliverableType], bigint>,
  'createPayment' : ActorMethod<
    [bigint, string, PaymentMethod, [] | [string]],
    bigint
  >,
  'createRequest' : ActorMethod<[ServiceType, string, Time], bigint>,
  'createVisitorRequest' : ActorMethod<[ServiceRequestInput], bigint>,
  'getAdminPaymentSettings' : ActorMethod<[], [] | [AdminPaymentSettings]>,
  'getAllDeliverables' : ActorMethod<[], Array<ComplianceDeliverable>>,
  'getAllDocuments' : ActorMethod<[], Array<ClientDocument>>,
  'getAllPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getAllPendingClients' : ActorMethod<[], Array<UserApprovalInfo>>,
  'getAllRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientApprovalStatus' : ActorMethod<[Principal], boolean>,
  'getClientDeliverables' : ActorMethod<
    [Principal],
    Array<ComplianceDeliverable>
  >,
  'getClientRequests' : ActorMethod<[Principal], Array<ServiceRequest>>,
  'getMyDeliverables' : ActorMethod<[], Array<ComplianceDeliverable>>,
  'getMyPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getMyPendingDeliverables' : ActorMethod<[], Array<ComplianceDeliverable>>,
  'getMyRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getPendingDeliverables' : ActorMethod<
    [Principal],
    Array<ComplianceDeliverable>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'rejectClient' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminPaymentSettings' : ActorMethod<[AdminPaymentSettings], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateDeliverableStatus' : ActorMethod<
    [bigint, DeliverableStatus],
    undefined
  >,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updateStatus' : ActorMethod<[bigint, RequestStatus], undefined>,
  'uploadDocument' : ActorMethod<
    [DocumentType, string, ExternalBlob],
    UploadDocumentResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];