/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const FollowUpStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const TimelineStatus = IDL.Variant({
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ToDoPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ToDoStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ToDoDocument = IDL.Record({
  'file' : ExternalBlob,
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
});
export const DeliverableType = IDL.Variant({
  'consulting' : IDL.Null,
  'annual' : IDL.Null,
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'creditCard' : IDL.Null,
  'applePay' : IDL.Null,
  'googlePay' : IDL.Null,
  'debitCard' : IDL.Null,
  'paypal' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'bankReconciliation' : IDL.Null,
  'accountingServices' : IDL.Null,
  'incomeTaxFiling' : IDL.Null,
  'gstFiling' : IDL.Null,
  'financialManagement' : IDL.Null,
  'other' : IDL.Null,
  'tdsFiling' : IDL.Null,
  'audits' : IDL.Null,
  'corporateTaxFiling' : IDL.Null,
  'payrollAdmin' : IDL.Null,
  'ledgerMaintenance' : IDL.Null,
  'loanFinancing' : IDL.Null,
});
export const ServiceRequestInput = IDL.Record({
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : Time,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'phone' : IDL.Text,
});
export const AdminPaymentSettings = IDL.Record({ 'paypalEmail' : IDL.Text });
export const DeliverableStatus = IDL.Variant({
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'inReview' : IDL.Null,
  'rejected' : IDL.Null,
  'drafting' : IDL.Null,
});
export const ComplianceDeliverable = IDL.Record({
  'id' : IDL.Nat,
  'status' : DeliverableStatus,
  'client' : IDL.Principal,
  'title' : IDL.Text,
  'dueDate' : Time,
  'deliverableType' : DeliverableType,
});
export const DocumentType = IDL.Variant({
  'accountingServices' : IDL.Null,
  'gstFiling' : IDL.Null,
  'financialManagement' : IDL.Null,
  'tdsFiling' : IDL.Null,
  'payrollReport' : IDL.Null,
  'auditDoc' : IDL.Null,
  'taxFiling' : IDL.Null,
  'loanFinancing' : IDL.Null,
});
export const ClientDocument = IDL.Record({
  'id' : IDL.Nat,
  'client' : IDL.Principal,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'mimeType' : IDL.Text,
  'docType' : DocumentType,
  'uploadedAt' : Time,
});
export const FollowUpItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : FollowUpStatus,
  'title' : IDL.Text,
  'dueDate' : Time,
  'description' : IDL.Text,
  'clientPrincipal' : IDL.Opt(IDL.Principal),
  'notes' : IDL.Text,
  'clientReference' : IDL.Opt(IDL.Principal),
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'client' : IDL.Principal,
  'paymentMethod' : PaymentMethod,
  'cardType' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'currencyCode' : IDL.Text,
  'amount' : IDL.Nat,
});
export const RequestStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'client' : IDL.Principal,
  'serviceType' : ServiceType,
  'name' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'description' : IDL.Text,
  'deadline' : Time,
  'email' : IDL.Opt(IDL.Text),
  'company' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const ClientDeliverableStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const ClientDeliverable = IDL.Record({
  'id' : IDL.Nat,
  'status' : ClientDeliverableStatus,
  'title' : IDL.Text,
  'submitter' : IDL.Principal,
  'file' : ExternalBlob,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const TimelineEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : TimelineStatus,
  'title' : IDL.Text,
  'endDate' : Time,
  'description' : IDL.Text,
  'clientPrincipal' : IDL.Opt(IDL.Principal),
  'taskReference' : IDL.Opt(IDL.Nat),
  'startDate' : Time,
});
export const ToDoItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : ToDoStatus,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'clientPrincipal' : IDL.Opt(IDL.Principal),
  'assignedClient' : IDL.Opt(IDL.Principal),
  'document' : IDL.Opt(ToDoDocument),
  'priority' : ToDoPriority,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
});
export const CompanyContactDetails = IDL.Record({
  'email' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const ExportFormat = IDL.Variant({
  'csv' : IDL.Null,
  'pdf' : IDL.Null,
  'zip' : IDL.Null,
  'docx' : IDL.Null,
  'xlsx' : IDL.Null,
  'image' : IDL.Null,
});
export const ExportableFile = IDL.Record({
  'id' : IDL.Nat,
  'originalFormat' : IDL.Text,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'availableFormats' : IDL.Vec(ExportFormat),
});
export const SearchIntentMetrics = IDL.Record({
  'localSeoRankings' : IDL.Nat,
  'seasonalKeywordTrends' : IDL.Vec(IDL.Text),
  'aiVisibilityScore' : IDL.Nat,
});
export const TrustMetrics = IDL.Record({
  'testimonialClicks' : IDL.Nat,
  'blogEngagement' : IDL.Nat,
  'aboutPageAvgTime' : IDL.Nat,
});
export const TechnicalReliabilityMetrics = IDL.Record({
  'pageLoadMs' : IDL.Nat,
  'sslStatus' : IDL.Bool,
  'mobileScore' : IDL.Nat,
});
export const LeadGenerationMetrics = IDL.Record({
  'leadQualityBreakup' : IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'medium' : IDL.Nat,
  }),
  'formSubmissions' : IDL.Nat,
  'clickToCallCount' : IDL.Nat,
});
export const ClientRetentionMetrics = IDL.Record({
  'portalFunnelDropoffs' : IDL.Nat,
  'returningUserRatio' : IDL.Float64,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const ClientDeliverableInput = IDL.Record({
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'description' : IDL.Text,
});
export const AdminClientDeliverableInput = IDL.Record({
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'clientPrincipal' : IDL.Principal,
});
export const UploadDocumentResult = IDL.Variant({
  'ok' : IDL.Nat,
  'notApproved' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClientFollowUp' : IDL.Func(
      [IDL.Text, IDL.Text, Time, FollowUpStatus, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createClientTimeline' : IDL.Func(
      [IDL.Text, IDL.Text, Time, Time, TimelineStatus],
      [IDL.Nat],
      [],
    ),
  'createClientToDo' : IDL.Func(
      [IDL.Text, IDL.Text, ToDoPriority, ToDoStatus, IDL.Opt(ToDoDocument)],
      [IDL.Nat],
      [],
    ),
  'createDeliverable' : IDL.Func(
      [IDL.Principal, IDL.Text, Time, DeliverableType],
      [IDL.Nat],
      [],
    ),
  'createFollowUp' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Opt(IDL.Principal),
        FollowUpStatus,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createPayment' : IDL.Func(
      [IDL.Nat, IDL.Text, PaymentMethod, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createRequest' : IDL.Func([ServiceType, IDL.Text, Time], [IDL.Nat], []),
  'createTimelineEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Time,
        Time,
        TimelineStatus,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Principal),
      ],
      [IDL.Nat],
      [],
    ),
  'createToDo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ToDoPriority,
        ToDoStatus,
        IDL.Opt(IDL.Principal),
        IDL.Opt(ToDoDocument),
      ],
      [IDL.Nat],
      [],
    ),
  'createVisitorRequest' : IDL.Func([ServiceRequestInput], [IDL.Nat], []),
  'getAdminPaymentSettings' : IDL.Func(
      [],
      [IDL.Opt(AdminPaymentSettings)],
      ['query'],
    ),
  'getAllComplianceDeliverables' : IDL.Func(
      [],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getAllDeliverables' : IDL.Func(
      [],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(ClientDocument)], ['query']),
  'getAllFollowUps' : IDL.Func([], [IDL.Vec(FollowUpItem)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getAllSubmittedDeliverables' : IDL.Func(
      [],
      [IDL.Vec(ClientDeliverable)],
      ['query'],
    ),
  'getAllTimelines' : IDL.Func([], [IDL.Vec(TimelineEntry)], ['query']),
  'getAllToDos' : IDL.Func([], [IDL.Vec(ToDoItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientDeliverables' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getClientDocuments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ClientDocument)],
      ['query'],
    ),
  'getClientRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getClientSubmissions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ClientDeliverable)],
      ['query'],
    ),
  'getCompanyContactDetails' : IDL.Func([], [CompanyContactDetails], ['query']),
  'getExportableFiles' : IDL.Func([], [IDL.Vec(ExportableFile)], ['query']),
  'getMyDeliverables' : IDL.Func(
      [],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getMyDocuments' : IDL.Func([], [IDL.Vec(ClientDocument)], ['query']),
  'getMyFollowUps' : IDL.Func([], [IDL.Vec(FollowUpItem)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getMyPendingDeliverables' : IDL.Func(
      [],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getMyRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getMySubmittedDeliverables' : IDL.Func(
      [],
      [IDL.Vec(ClientDeliverable)],
      ['query'],
    ),
  'getMyTimelines' : IDL.Func([], [IDL.Vec(TimelineEntry)], ['query']),
  'getMyToDos' : IDL.Func([], [IDL.Vec(ToDoItem)], ['query']),
  'getNewAnalyticsSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'searchIntent' : SearchIntentMetrics,
          'trust' : TrustMetrics,
          'technicalReliability' : TechnicalReliabilityMetrics,
          'leadGeneration' : LeadGenerationMetrics,
          'clientRetention' : ClientRetentionMetrics,
        }),
      ],
      ['query'],
    ),
  'getPendingDeliverables' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ComplianceDeliverable)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminPaymentSettings' : IDL.Func([AdminPaymentSettings], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitDeliverable' : IDL.Func([ClientDeliverableInput], [IDL.Nat], []),
  'submitDeliverableForClient' : IDL.Func(
      [AdminClientDeliverableInput],
      [IDL.Nat],
      [],
    ),
  'updateClientDeliverableStatus' : IDL.Func(
      [IDL.Nat, ClientDeliverableStatus],
      [],
      [],
    ),
  'updateCompanyContactDetails' : IDL.Func([CompanyContactDetails], [], []),
  'updateFollowUpStatus' : IDL.Func([IDL.Nat, FollowUpStatus], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updateStatus' : IDL.Func([IDL.Nat, RequestStatus], [], []),
  'updateTimelineStatus' : IDL.Func([IDL.Nat, TimelineStatus], [], []),
  'updateToDoStatus' : IDL.Func([IDL.Nat, ToDoStatus], [], []),
  'uploadDocument' : IDL.Func(
      [DocumentType, IDL.Text, IDL.Text, ExternalBlob],
      [UploadDocumentResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const FollowUpStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const TimelineStatus = IDL.Variant({
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ToDoPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ToDoStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ToDoDocument = IDL.Record({
    'file' : ExternalBlob,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
  });
  const DeliverableType = IDL.Variant({
    'consulting' : IDL.Null,
    'annual' : IDL.Null,
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'creditCard' : IDL.Null,
    'applePay' : IDL.Null,
    'googlePay' : IDL.Null,
    'debitCard' : IDL.Null,
    'paypal' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'bankReconciliation' : IDL.Null,
    'accountingServices' : IDL.Null,
    'incomeTaxFiling' : IDL.Null,
    'gstFiling' : IDL.Null,
    'financialManagement' : IDL.Null,
    'other' : IDL.Null,
    'tdsFiling' : IDL.Null,
    'audits' : IDL.Null,
    'corporateTaxFiling' : IDL.Null,
    'payrollAdmin' : IDL.Null,
    'ledgerMaintenance' : IDL.Null,
    'loanFinancing' : IDL.Null,
  });
  const ServiceRequestInput = IDL.Record({
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : Time,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AdminPaymentSettings = IDL.Record({ 'paypalEmail' : IDL.Text });
  const DeliverableStatus = IDL.Variant({
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'inReview' : IDL.Null,
    'rejected' : IDL.Null,
    'drafting' : IDL.Null,
  });
  const ComplianceDeliverable = IDL.Record({
    'id' : IDL.Nat,
    'status' : DeliverableStatus,
    'client' : IDL.Principal,
    'title' : IDL.Text,
    'dueDate' : Time,
    'deliverableType' : DeliverableType,
  });
  const DocumentType = IDL.Variant({
    'accountingServices' : IDL.Null,
    'gstFiling' : IDL.Null,
    'financialManagement' : IDL.Null,
    'tdsFiling' : IDL.Null,
    'payrollReport' : IDL.Null,
    'auditDoc' : IDL.Null,
    'taxFiling' : IDL.Null,
    'loanFinancing' : IDL.Null,
  });
  const ClientDocument = IDL.Record({
    'id' : IDL.Nat,
    'client' : IDL.Principal,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'mimeType' : IDL.Text,
    'docType' : DocumentType,
    'uploadedAt' : Time,
  });
  const FollowUpItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : FollowUpStatus,
    'title' : IDL.Text,
    'dueDate' : Time,
    'description' : IDL.Text,
    'clientPrincipal' : IDL.Opt(IDL.Principal),
    'notes' : IDL.Text,
    'clientReference' : IDL.Opt(IDL.Principal),
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'client' : IDL.Principal,
    'paymentMethod' : PaymentMethod,
    'cardType' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'currencyCode' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const RequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'client' : IDL.Principal,
    'serviceType' : ServiceType,
    'name' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'description' : IDL.Text,
    'deadline' : Time,
    'email' : IDL.Opt(IDL.Text),
    'company' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const ClientDeliverableStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const ClientDeliverable = IDL.Record({
    'id' : IDL.Nat,
    'status' : ClientDeliverableStatus,
    'title' : IDL.Text,
    'submitter' : IDL.Principal,
    'file' : ExternalBlob,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const TimelineEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : TimelineStatus,
    'title' : IDL.Text,
    'endDate' : Time,
    'description' : IDL.Text,
    'clientPrincipal' : IDL.Opt(IDL.Principal),
    'taskReference' : IDL.Opt(IDL.Nat),
    'startDate' : Time,
  });
  const ToDoItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : ToDoStatus,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'clientPrincipal' : IDL.Opt(IDL.Principal),
    'assignedClient' : IDL.Opt(IDL.Principal),
    'document' : IDL.Opt(ToDoDocument),
    'priority' : ToDoPriority,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
  });
  const CompanyContactDetails = IDL.Record({
    'email' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const ExportFormat = IDL.Variant({
    'csv' : IDL.Null,
    'pdf' : IDL.Null,
    'zip' : IDL.Null,
    'docx' : IDL.Null,
    'xlsx' : IDL.Null,
    'image' : IDL.Null,
  });
  const ExportableFile = IDL.Record({
    'id' : IDL.Nat,
    'originalFormat' : IDL.Text,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'availableFormats' : IDL.Vec(ExportFormat),
  });
  const SearchIntentMetrics = IDL.Record({
    'localSeoRankings' : IDL.Nat,
    'seasonalKeywordTrends' : IDL.Vec(IDL.Text),
    'aiVisibilityScore' : IDL.Nat,
  });
  const TrustMetrics = IDL.Record({
    'testimonialClicks' : IDL.Nat,
    'blogEngagement' : IDL.Nat,
    'aboutPageAvgTime' : IDL.Nat,
  });
  const TechnicalReliabilityMetrics = IDL.Record({
    'pageLoadMs' : IDL.Nat,
    'sslStatus' : IDL.Bool,
    'mobileScore' : IDL.Nat,
  });
  const LeadGenerationMetrics = IDL.Record({
    'leadQualityBreakup' : IDL.Record({
      'low' : IDL.Nat,
      'high' : IDL.Nat,
      'medium' : IDL.Nat,
    }),
    'formSubmissions' : IDL.Nat,
    'clickToCallCount' : IDL.Nat,
  });
  const ClientRetentionMetrics = IDL.Record({
    'portalFunnelDropoffs' : IDL.Nat,
    'returningUserRatio' : IDL.Float64,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const ClientDeliverableInput = IDL.Record({
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'description' : IDL.Text,
  });
  const AdminClientDeliverableInput = IDL.Record({
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'clientPrincipal' : IDL.Principal,
  });
  const UploadDocumentResult = IDL.Variant({
    'ok' : IDL.Nat,
    'notApproved' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClientFollowUp' : IDL.Func(
        [IDL.Text, IDL.Text, Time, FollowUpStatus, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createClientTimeline' : IDL.Func(
        [IDL.Text, IDL.Text, Time, Time, TimelineStatus],
        [IDL.Nat],
        [],
      ),
    'createClientToDo' : IDL.Func(
        [IDL.Text, IDL.Text, ToDoPriority, ToDoStatus, IDL.Opt(ToDoDocument)],
        [IDL.Nat],
        [],
      ),
    'createDeliverable' : IDL.Func(
        [IDL.Principal, IDL.Text, Time, DeliverableType],
        [IDL.Nat],
        [],
      ),
    'createFollowUp' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Opt(IDL.Principal),
          FollowUpStatus,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, PaymentMethod, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createRequest' : IDL.Func([ServiceType, IDL.Text, Time], [IDL.Nat], []),
    'createTimelineEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          Time,
          TimelineStatus,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Principal),
        ],
        [IDL.Nat],
        [],
      ),
    'createToDo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ToDoPriority,
          ToDoStatus,
          IDL.Opt(IDL.Principal),
          IDL.Opt(ToDoDocument),
        ],
        [IDL.Nat],
        [],
      ),
    'createVisitorRequest' : IDL.Func([ServiceRequestInput], [IDL.Nat], []),
    'getAdminPaymentSettings' : IDL.Func(
        [],
        [IDL.Opt(AdminPaymentSettings)],
        ['query'],
      ),
    'getAllComplianceDeliverables' : IDL.Func(
        [],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getAllDeliverables' : IDL.Func(
        [],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(ClientDocument)], ['query']),
    'getAllFollowUps' : IDL.Func([], [IDL.Vec(FollowUpItem)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getAllSubmittedDeliverables' : IDL.Func(
        [],
        [IDL.Vec(ClientDeliverable)],
        ['query'],
      ),
    'getAllTimelines' : IDL.Func([], [IDL.Vec(TimelineEntry)], ['query']),
    'getAllToDos' : IDL.Func([], [IDL.Vec(ToDoItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientDeliverables' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getClientDocuments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ClientDocument)],
        ['query'],
      ),
    'getClientRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getClientSubmissions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ClientDeliverable)],
        ['query'],
      ),
    'getCompanyContactDetails' : IDL.Func(
        [],
        [CompanyContactDetails],
        ['query'],
      ),
    'getExportableFiles' : IDL.Func([], [IDL.Vec(ExportableFile)], ['query']),
    'getMyDeliverables' : IDL.Func(
        [],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getMyDocuments' : IDL.Func([], [IDL.Vec(ClientDocument)], ['query']),
    'getMyFollowUps' : IDL.Func([], [IDL.Vec(FollowUpItem)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getMyPendingDeliverables' : IDL.Func(
        [],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getMyRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getMySubmittedDeliverables' : IDL.Func(
        [],
        [IDL.Vec(ClientDeliverable)],
        ['query'],
      ),
    'getMyTimelines' : IDL.Func([], [IDL.Vec(TimelineEntry)], ['query']),
    'getMyToDos' : IDL.Func([], [IDL.Vec(ToDoItem)], ['query']),
    'getNewAnalyticsSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'searchIntent' : SearchIntentMetrics,
            'trust' : TrustMetrics,
            'technicalReliability' : TechnicalReliabilityMetrics,
            'leadGeneration' : LeadGenerationMetrics,
            'clientRetention' : ClientRetentionMetrics,
          }),
        ],
        ['query'],
      ),
    'getPendingDeliverables' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ComplianceDeliverable)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminPaymentSettings' : IDL.Func([AdminPaymentSettings], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitDeliverable' : IDL.Func([ClientDeliverableInput], [IDL.Nat], []),
    'submitDeliverableForClient' : IDL.Func(
        [AdminClientDeliverableInput],
        [IDL.Nat],
        [],
      ),
    'updateClientDeliverableStatus' : IDL.Func(
        [IDL.Nat, ClientDeliverableStatus],
        [],
        [],
      ),
    'updateCompanyContactDetails' : IDL.Func([CompanyContactDetails], [], []),
    'updateFollowUpStatus' : IDL.Func([IDL.Nat, FollowUpStatus], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updateStatus' : IDL.Func([IDL.Nat, RequestStatus], [], []),
    'updateTimelineStatus' : IDL.Func([IDL.Nat, TimelineStatus], [], []),
    'updateToDoStatus' : IDL.Func([IDL.Nat, ToDoStatus], [], []),
    'uploadDocument' : IDL.Func(
        [DocumentType, IDL.Text, IDL.Text, ExternalBlob],
        [UploadDocumentResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };