/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPaymentSettings { 'paypalEmail' : string }
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ClientDeliverable {
  'id' : bigint,
  'status' : ClientDeliverableStatus,
  'title' : string,
  'submitter' : Principal,
  'file' : ExternalBlob,
  'createdAt' : Time,
  'description' : string,
}
export interface ClientDeliverableInput {
  'title' : string,
  'file' : ExternalBlob,
  'description' : string,
}
export type ClientDeliverableStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface ClientDocument {
  'id' : bigint,
  'client' : Principal,
  'file' : ExternalBlob,
  'name' : string,
  'docType' : DocumentType,
  'uploadedAt' : Time,
}
export interface ClientRetentionMetrics {
  'portalFunnelDropoffs' : bigint,
  'returningUserRatio' : number,
}
export interface ComplianceDeliverable {
  'id' : bigint,
  'status' : DeliverableStatus,
  'client' : Principal,
  'title' : string,
  'dueDate' : Time,
  'deliverableType' : DeliverableType,
}
export interface DeadlineRecord {
  'id' : bigint,
  'status' : DeadlineStatus,
  'title' : string,
  'urgencyLevel' : UrgencyLevel,
  'dueDate' : Time,
  'description' : string,
  'clientPrincipal' : [] | [Principal],
  'deliverableReference' : [] | [bigint],
}
export type DeadlineStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'missed' : null };
export type DeliverableStatus = { 'completed' : null } |
  { 'approved' : null } |
  { 'inReview' : null } |
  { 'rejected' : null } |
  { 'drafting' : null };
export type DeliverableType = { 'consulting' : null } |
  { 'annual' : null } |
  { 'quarterly' : null } |
  { 'monthly' : null };
export type DocumentType = { 'payrollReport' : null } |
  { 'auditDoc' : null } |
  { 'taxFiling' : null };
export type ExternalBlob = Uint8Array;
export interface FollowUpItem {
  'id' : bigint,
  'status' : FollowUpStatus,
  'title' : string,
  'dueDate' : Time,
  'description' : string,
  'clientPrincipal' : [] | [Principal],
  'notes' : string,
  'clientReference' : [] | [Principal],
}
export type FollowUpStatus = { 'pending' : null } |
  { 'completed' : null };
export interface LeadGenerationMetrics {
  'leadQualityBreakup' : { 'low' : bigint, 'high' : bigint, 'medium' : bigint },
  'formSubmissions' : bigint,
  'clickToCallCount' : bigint,
}
export type PaymentMethod = { 'creditCard' : null } |
  { 'applePay' : null } |
  { 'googlePay' : null } |
  { 'debitCard' : null } |
  { 'paypal' : null };
export interface PaymentRecord {
  'id' : bigint,
  'status' : PaymentStatus,
  'client' : Principal,
  'paymentMethod' : PaymentMethod,
  'cardType' : [] | [string],
  'timestamp' : Time,
  'currencyCode' : string,
  'amount' : bigint,
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type RequestStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface SearchIntentMetrics {
  'localSeoRankings' : bigint,
  'seasonalKeywordTrends' : Array<string>,
  'aiVisibilityScore' : bigint,
}
export interface ServiceRequest {
  'id' : bigint,
  'status' : RequestStatus,
  'client' : Principal,
  'serviceType' : ServiceType,
  'name' : [] | [string],
  'createdAt' : Time,
  'description' : string,
  'deadline' : Time,
  'email' : [] | [string],
  'company' : [] | [string],
  'phone' : [] | [string],
}
export interface ServiceRequestInput {
  'serviceType' : ServiceType,
  'name' : string,
  'description' : string,
  'deadline' : Time,
  'email' : string,
  'company' : string,
  'phone' : string,
}
export type ServiceType = { 'bankReconciliation' : null } |
  { 'incomeTaxFiling' : null } |
  { 'other' : null } |
  { 'audits' : null } |
  { 'corporateTaxFiling' : null } |
  { 'payrollAdmin' : null } |
  { 'ledgerMaintenance' : null };
export interface TechnicalReliabilityMetrics {
  'pageLoadMs' : bigint,
  'sslStatus' : boolean,
  'mobileScore' : bigint,
}
export type Time = bigint;
export interface TimelineEntry {
  'id' : bigint,
  'status' : TimelineStatus,
  'title' : string,
  'endDate' : Time,
  'description' : string,
  'clientPrincipal' : [] | [Principal],
  'taskReference' : [] | [bigint],
  'startDate' : Time,
}
export type TimelineStatus = { 'completed' : null } |
  { 'planned' : null } |
  { 'inProgress' : null };
export interface ToDoItem {
  'id' : bigint,
  'status' : ToDoStatus,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'clientPrincipal' : [] | [Principal],
  'assignedClient' : [] | [Principal],
  'priority' : ToDoPriority,
}
export type ToDoPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type ToDoStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface TrustMetrics {
  'testimonialClicks' : bigint,
  'blogEngagement' : bigint,
  'aboutPageAvgTime' : bigint,
}
export type UploadDocumentResult = { 'ok' : bigint } |
  { 'notApproved' : null };
export type UrgencyLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClientDeadline' : ActorMethod<
    [string, string, Time, UrgencyLevel, DeadlineStatus],
    bigint
  >,
  'createClientFollowUp' : ActorMethod<
    [string, string, Time, FollowUpStatus, string],
    bigint
  >,
  'createClientTimeline' : ActorMethod<
    [string, string, Time, Time, TimelineStatus],
    bigint
  >,
  'createClientToDo' : ActorMethod<
    [string, string, ToDoPriority, ToDoStatus],
    bigint
  >,
  'createDeadline' : ActorMethod<
    [string, string, Time, UrgencyLevel, DeadlineStatus, [] | [bigint]],
    bigint
  >,
  'createDeliverable' : ActorMethod<
    [Principal, string, Time, DeliverableType],
    bigint
  >,
  'createFollowUp' : ActorMethod<
    [string, string, Time, [] | [Principal], FollowUpStatus, string],
    bigint
  >,
  'createPayment' : ActorMethod<
    [bigint, string, PaymentMethod, [] | [string]],
    bigint
  >,
  'createRequest' : ActorMethod<[ServiceType, string, Time], bigint>,
  'createTimelineEntry' : ActorMethod<
    [string, string, Time, Time, TimelineStatus, [] | [bigint]],
    bigint
  >,
  'createToDo' : ActorMethod<
    [string, string, ToDoPriority, ToDoStatus, [] | [Principal]],
    bigint
  >,
  'createVisitorRequest' : ActorMethod<[ServiceRequestInput], bigint>,
  'getAdminPaymentSettings' : ActorMethod<[], [] | [AdminPaymentSettings]>,
  'getAllComplianceDeliverables' : ActorMethod<
    [],
    Array<ComplianceDeliverable>
  >,
  'getAllDeadlines' : ActorMethod<[], Array<DeadlineRecord>>,
  'getAllDeliverables' : ActorMethod<[], Array<ComplianceDeliverable>>,
  'getAllDocuments' : ActorMethod<[], Array<ClientDocument>>,
  'getAllFollowUps' : ActorMethod<[], Array<FollowUpItem>>,
  'getAllPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getAllRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getAllSubmittedDeliverables' : ActorMethod<[], Array<ClientDeliverable>>,
  'getAllTimelines' : ActorMethod<[], Array<TimelineEntry>>,
  'getAllToDos' : ActorMethod<[], Array<ToDoItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientDeliverables' : ActorMethod<
    [Principal],
    Array<ComplianceDeliverable>
  >,
  'getClientRequests' : ActorMethod<[Principal], Array<ServiceRequest>>,
  'getClientSubmissions' : ActorMethod<[Principal], Array<ClientDeliverable>>,
  'getMyDeadlines' : ActorMethod<[], Array<DeadlineRecord>>,
  'getMyDeliverables' : ActorMethod<[], Array<ComplianceDeliverable>>,
  'getMyFollowUps' : ActorMethod<[], Array<FollowUpItem>>,
  'getMyPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getMyPendingDeliverables' : ActorMethod<[], Array<ComplianceDeliverable>>,
  'getMyRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getMySubmittedDeliverables' : ActorMethod<[], Array<ClientDeliverable>>,
  'getMyTimelines' : ActorMethod<[], Array<TimelineEntry>>,
  'getMyToDos' : ActorMethod<[], Array<ToDoItem>>,
  'getNewAnalyticsSummary' : ActorMethod<
    [],
    {
      'searchIntent' : SearchIntentMetrics,
      'trust' : TrustMetrics,
      'technicalReliability' : TechnicalReliabilityMetrics,
      'leadGeneration' : LeadGenerationMetrics,
      'clientRetention' : ClientRetentionMetrics,
    }
  >,
  'getPendingDeliverables' : ActorMethod<
    [Principal],
    Array<ComplianceDeliverable>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminPaymentSettings' : ActorMethod<[AdminPaymentSettings], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitDeliverable' : ActorMethod<[ClientDeliverableInput], bigint>,
  'updateClientDeadlineStatus' : ActorMethod<
    [bigint, DeadlineStatus],
    undefined
  >,
  'updateClientDeliverableStatus' : ActorMethod<
    [bigint, ClientDeliverableStatus],
    undefined
  >,
  'updateClientFollowUpStatus' : ActorMethod<
    [bigint, FollowUpStatus],
    undefined
  >,
  'updateClientTimelineStatus' : ActorMethod<
    [bigint, TimelineStatus],
    undefined
  >,
  'updateClientToDoStatus' : ActorMethod<[bigint, ToDoStatus], undefined>,
  'updateDeadlineStatus' : ActorMethod<[bigint, DeadlineStatus], undefined>,
  'updateFollowUpStatus' : ActorMethod<[bigint, FollowUpStatus], undefined>,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updateStatus' : ActorMethod<[bigint, RequestStatus], undefined>,
  'updateTimelineStatus' : ActorMethod<[bigint, TimelineStatus], undefined>,
  'updateToDoStatus' : ActorMethod<[bigint, ToDoStatus], undefined>,
  'uploadDocument' : ActorMethod<
    [DocumentType, string, ExternalBlob],
    UploadDocumentResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];